import { Theme, Container } from "@radix-ui/themes";
import "@radix-ui/themes/layout.css";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";
import { ThemeProvider } from "next-themes";
import { GlobalNavigation } from "./_components/GlobalNavigation/index";
import { ThemeToggle } from "./_components/ThemeToggle";

const headingMono = IBM_Plex_Sans({
  variable: "--font-heading",
  style: "normal",
  subsets: ["latin"],
  weight: "300",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${headingMono.variable}`}>
        <ThemeProvider attribute="class">
          <Theme
            accentColor="cyan"
            radius="medium"
            scaling="110%"
            hasBackground={false}
          >
            <Container p="6" size="4">
              <GlobalNavigation />
              <ThemeToggle className={styles.ThemeToggleButton} />
              <main>
                <Container p="6">{children}</Container>
              </main>
            </Container>
          </Theme>
        </ThemeProvider>
      </body>
    </html>
  );
}
