import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/layout.css";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { GlobalNavigation } from "./_components/GlobalNavigation/index";

const headingMono = IBM_Plex_Mono({
  variable: "--font-heading",
  style: "normal",
  subsets: ["latin"],
  weight: "300",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${headingMono.variable}`}>
        <ThemeProvider attribute="class">
          <Theme
            accentColor="cyan"
            panelBackground="solid"
            radius="none"
            scaling="110%"
          >
            <GlobalNavigation
              data={[
                {
                  title: "Login",
                },
              ]}
            />
            <main>{children}</main>
          </Theme>
        </ThemeProvider>
      </body>
    </html>
  );
}
